services:
  app:
    container_name: problems_app
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - .:/var/problems
